#!/bin/bash

RESIZE_AMOUNT=100
SPACES_PER_DISPLAY=3

function yabai_message() {
  type=$1
  action=$2
  subaction=$3
  modifier=$4
  /opt/homebrew/bin/yabai -m "$type" "--$action" "$subaction" "$modifier"
}

function spaces_on_display() {
  index=$1
  yabai_message "query" "spaces" "--display" "$index" | jq -r '.[].index'
}

function space_current_index() {
  yabai_message "query" "spaces" "--space" | jq -r '.index'
}

function window_current_id() {
  yabai_message "query" "windows" "--window" | jq -r '.id'
}

function space_next() {
  direction=$1
  spaces=$(spaces_on_display)
  index=$(space_current_index)

  if [ "$direction" = "north" ]; then
    index_next=$((index + 1))
  else
    index_next=$((index - 1))
  fi

  index_first=$(echo "$spaces" | head -n 1)
  index_last=$(echo "$spaces" | tail -n 1)

  if [ $index_next -gt $index_last ]; then
    echo $index_first
  elif [ $index_next -lt $index_first ]; then
    echo $index_last
  else
    echo $index_next
  fi
}

function displays_on_system() {
  yabai_message "query" "displays" "" | jq -r '.[].index'
}

function display_current_index() {
  yabai_message "query" "displays" "--display" | jq -r '.index'
}

function display_next() {
  direction=$1
  displays=$(displays_on_system)
  index=$(display_current_index)

  if [ "$direction" = "east" ]; then
    index_next=$((index + 1))
  else
    index_next=$((index - 1))
  fi

  index_first=$(echo "$displays" | head -n 1)
  index_last=$(echo "$displays" | tail -n 1)

  if [ $index_next -gt $index_last ]; then
    echo $index_first
  elif [ $index_next -lt $index_first ]; then
    echo $index_last
  else
    echo $index_next
  fi
}

function workspace_is_empty() {
  windows=$(yabai_message "query" "windows" "--space" | jq -r '.[] | select(.floating != 1 and .visible != 0 and .minimized != 1)')
  if [ -z "$windows" ]; then
    echo "true"
  else
    echo "false"
  fi
}

function position_adjacent() {
  direction=$1
  case $direction in
    "east") echo "first" ;;
    "west") echo "last" ;;
    "south") echo "first" ;;
    "north") echo "last" ;;
  esac
}

function yabai_focus() {
  direction=$1
  focus_adjacent_window=$(yabai_message "window" "focus" "$direction")
  status=$?

  if [ $status -ne 0 ]; then
    case $direction in
      "east"|"west")
        index=$(display_next "$direction")
        yabai_message "display" "focus" "$index"
        ;;
      "north"|"south")
        index=$(space_next "$direction")
        yabai_message "space" "focus" "$index"
        ;;
    esac

    if [ "$(workspace_is_empty)" = "false" ]; then
      position=$(position_adjacent "$direction")
      yabai_message "window" "focus" "$position"
    fi
  fi
}

function yabai_move() {
  direction=$1
  warp_adjacent_window=$(yabai_message "window" "swap" "$direction")
  status=$?

  if [ $status -ne 0 ]; then
    id=$(window_current_id)

    case $direction in
      "east"|"west")
        index=$(display_next "$direction")
        yabai_message "window" "display" "$index"
        yabai_message "display" "focus" "$index"
        ;;
      "north"|"south")
        index=$(space_next "$direction")
        yabai_message "window" "space" "$index"
        yabai_message "space" "focus" "$index"
        ;;
    esac

    position=$(position_adjacent "$direction")
    yabai_message "window" "warp" "$position"
    yabai_message "window" "focus" "$id"
  fi
}

function yabai_resize() {
  direction=$1
  case $direction in
    "west")
      yabai_message "window" "resize" "left:-${RESIZE_AMOUNT}:0" || yabai_message "window" "resize" "right:-${RESIZE_AMOUNT}:0"
      ;;
    "east")
      yabai_message "window" "resize" "left:${RESIZE_AMOUNT}:0" || yabai_message "window" "resize" "right:${RESIZE_AMOUNT}:0"
      ;;
    "north")
      yabai_message "window" "resize" "bottom:0:-${RESIZE_AMOUNT}" || yabai_message "window" "resize" "top:0:-${RESIZE_AMOUNT}"
      ;;
    "south")
      yabai_message "window" "resize" "bottom:0:${RESIZE_AMOUNT}" || yabai_message "window" "resize" "top:0:${RESIZE_AMOUNT}"
      ;;
  esac
}

function yabai_create_workspaces() {
  display_initial=$(display_current_index)
  space_initial=$(space_current_index)

  displays=$(displays_on_system)

  for di in $displays; do
    yabai_message "display" "focus" "$di"

    spaces=$(spaces_on_display "$di")
    spaces_count=$(echo "$spaces" | wc -l)

    for ((k = spaces_count; k <= SPACES_PER_DISPLAY; k++)); do
      yabai_message "space" "create"
    done
  done

  yabai_message "display" "focus" "$display_initial"
  yabai_message "space" "focus" "$space_initial"
}

action=$1
direction=$2

case $action in
  "focus")
    yabai_focus "$direction"
    ;;
  "move")
    yabai_move "$direction"
    ;;
  "resize")
    yabai_resize "$direction"
    ;;
  "create_workspaces")
    yabai_create_workspaces
    ;;
esac