{ config, lib, pkgs, options, ... }: {
  config.homebrew.taps = [];


  config.homebrew.brews = [ "colima" "docker" "docker-compose" ];
  config.homebrew.casks = [        
    "appcleaner"
    "balenaetcher"
    "basictex"
    "bitwig-studio"
    "boltai"
    "brave-browser"
    "discord"
    "disk-drill"
    "element"
    "firefox"
    "geekbench"
    "gimp"
    "grandperspective"
    "handbrake"
    "inkscape"
    "wezterm"
    "karabiner-elements"
    "krita"
    "launchcontrol"
    "libreoffice"
    "little-snitch"
    "obs"
    "obsidian"
    "ollama"
    "openvpn-connect"
    "protonmail-bridge"
    "protonvpn"
    "raycast"
    "resilio-sync"
    "spotify"
    "the-unarchiver"
    "transmission"
    "utm"
    "visual-studio-code"
    "vlc"
    "zed"
    "zed@preview"
    # "blender"
    # "charles"
    # "darktable"
    # "dash"
    # "docker"
    # "musescore"
    # "vscodium"
    # "wireshark"
  ];
}
