{ config, lib, pkgs, options, ... }: {
  imports = [ ./modules.nix ];
  
  config.homebrew.casks = [        
    "appcleaner"
    "balenaetcher"
    "balenaetcher"
    "bitwig-studio"
    # "blender"
    "brave-browser"
    "charles"
    "chromium"
    "contexts"
    "darktable"
    "dash"
    "disk-drill"
    "discord"
    # "docker"
    "element"
    "firefox"
    "geekbench"
    "gimp"
    "grandperspective"
    "handbrake"
    "inkscape"
    "iterm2"
    "karabiner-elements"
    "krita"
    "launchcontrol"
    "libreoffice"
    "little-snitch"
    "musescore"
    "notion"
    "obs"
    "obsidian"
    "openvpn-connect"
    "protonmail-bridge"
    "protonvpn"
    "resilio-sync"
    "spotify"
    "the-unarchiver"
    "transmission"
    "visual-studio-code"
    "vlc"
    "wireshark"
    "zenmap"
    "adobe-creative-cloud"
  ];
}
